branch-defaults:
  master:
    environment: ImageFilter-Development
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: ImageFilter
  branch: null
  default_ec2_keyname: <KEY_NAME>
  default_platform: Node.js
  default_region: <REGION>
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
